### PR TITLE
Add some notes

### PR DESCRIPTION
**Pull request by datawookie**
Hi @GavinMasterson, I've added some notes in the script about how to mount your local folder as the ~/Downloads folder on the Selenium container. Give it a try. Let me know if you are still having trouble and we can have a quick call so I can show you what needs to be done. I'm sure you should have it sorted now though. Thanks, Andrew.

### CODE REVIEW

**Comment by datawookie** [comment]
Did that help?

**Comment by GavinMasterson** [comment]
Hi Andrew  How is lockdown going for you? This pandemic sure escalated quickly when I think back to satRday2020 which was my last big gathering for the last two months. Under normal circumstances I would have been in the UK at Exeter University, but instead I’m currently in Knysna with my wife and son, with a stunning view of the lagoon so I’m feeling super privileged.  Thanks for looking at this docker query of mine. Sorry for the delayed response - I’ve had no chance to play around with this web scraper until today as I’m on fulltime dad regime with a two-year old and braindead at night. Sadly, I’m encountering the same issue even with the ${PwD} insertion you added: the file downloads into the Chrome default downloads folder but not the folder on my C drive. Just for clarification, when I run the docker commands at the start should I run the two -v commands or just the one?In other words, this: docker run -d --rm \   --name selenium \   -p 4444:4444 \   -p 5900:5900 \   -v ${PwD}:C:/invasive_herps/downloads \   -v ${PwD}:/home/seluser/Downloads \   selenium/standalone-chrome-debug:3.141 or this: docker run -d --rm \   --name selenium \   -p 4444:4444 \   -p 5900:5900 \   -v ${PwD}:C:/invasive_herps/downloads \   selenium/standalone-chrome-debug:3.141 The container runs in both cases but the file still goes in to the default downloads folder set by Chrome.  This is totally in character for me as I always do this with things I learn – I try to apply them in ways that immediately stretch me far and inevitably run into these little obstacles 😊  I’m free for a call if you are and we can try to debug it, but please feel no pressure. I’m not in any rush at all with this. All the best,Gavin  From: Andrew CollierSent: Saturday, 14 March 2020 06:40To: GavinMasterson/invasive_herpsCc: Gavin Masterson; MentionSubject: [GavinMasterson/invasive_herps] Add some notes (#1) Hi @GavinMasterson, I've added some notes in the script about how to mount your local folder as the ~/Downloads folder on the Selenium container. Give it a try. Let me know if you are still having trouble and we can have a quick call so I can show you what needs to be done. I'm sure you should have it sorted now though. Thanks, Andrew.You can view, comment on, or merge this pull request online at:  https://github.com/GavinMasterson/invasive_herps/pull/1Commit SummaryAdd some notesFile ChangesM dynamic_scraper_GISD.R (24) Patch Links:https://github.com/GavinMasterson/invasive_herps/pull/1.patchhttps://github.com/GavinMasterson/invasive_herps/pull/1.diff—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by datawookie** [comment]
> Just for clarification, when I run the docker commands at the start should I run the two -v commands or just the one?In other words, this: `docker run -d --rm --name selenium -p 4444:4444 -p 5900:5900 -v ${PwD}:C:/invasive_herps/downloads -v ${PwD}:/home/seluser/Downloads selenium/standalone-chrome-debug:3.141` or this: `docker run -d --rm --name selenium -p 4444:4444 -p 5900:5900 -v ${PwD}:C:/invasive_herps/downloads selenium/standalone-chrome-debug:3.141`

I don't think that either of those options corresponds to the suggestions. :)

**Comment by datawookie** [comment]
Please take a look at the suggestions and try again. I think that one of these options should work:

```
docker run -d --rm \
   --name selenium \
   -p 4444:4444 \
   -p 5900:5900 \
   -v $(pwd):/home/seluser/Downloads \
   selenium/standalone-chrome-debug:3.141
```

```
docker run -d --rm \
   --name selenium \
   -p 4444:4444 \
   -p 5900:5900 \
   -v %cd%:/home/seluser/Downloads \
   selenium/standalone-chrome-debug:3.141
```

```
docker run -d --rm \
   --name selenium \
   -p 4444:4444 \
   -p 5900:5900 \
   -v ${PWD}:/home/seluser/Downloads \
   selenium/standalone-chrome-debug:3.141
```

If none of these works (because I know little or nothing about Windows!) then I'm very happy to have a call.

**Comment by GavinMasterson** [comment]
Will do.
My son woke up from his nap so it'll be this evening and I'll get back to
you.

Thanks again.
Gavin

**Pull request merged**
